# The self variable in python explained

This tutorial is based on [this site](https://pythontips.com/2013/08/07/the-self-variable-in-python-explained/).I was learning DFA about binary tree and I need to store node infromation in a new class. The question is broke into building a easy-to-use class and I think self variable in python is quite necessary. 

In [6]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

**A simple class :**

So here is our class:

In [2]:
class Restaurant(object):
    bankrupt = False
    def open_branch(self):
        if not self.bankrupt:
            print("branch opened")

We can explain the code without any technicalityies.First we define a class use code above. Then we assign it a property "bankrupt" which defaults to be False.After that we define a function called open_branch which can only occur if "bankrupt" is False which means the restaurant has some money.

**Making a restaurant**

Now that we have made a class for a Restaurant, lets actually make a restaurant:

In [3]:
x = Restaurant()

Now x is a Restaurant which has a property bankrupt and a function open_branch. After we define x is a Restaurant, we can access the property bankrupt by typing:

In [6]:
x.bankrupt
Restaurant().bankrupt
Restaurant.bankrupt

False

False

False

The first argument of every class method, including **init**, is always a reference to the current instance(实例) of the class. By convention, this argument is always named self. In the **init** method, self refers to the newly created object; in other class methods, it refers to the instance whose method was called. For example the below code is the same as the above code.

**Free Tip:**

However self is not a reserved keyword in python it’s just a strong convention. Many people say that why do we have to write self ? Why can’t we have it set automatically like in Java ? Someone also filed a PEP (improvement suggestion) in which he suggested to remove the explicit assignment of self keyword. However Guido Van Rossum (the maker of python) wrote a [blogpost in which he told why explicit self has to stay](http://neopythonic.blogspot.com/2008/10/why-explicit-self-has-to-stay.html).

In [8]:
exec('print(123)')

123


In [9]:
def bar(first, second, third, **options):
    if options.get("action") == "sum":
        print("The sum is: %d" %(first + second + third))

    if options.get("number") == "first":
        return first

result = bar(1, 2, 3, action = "sum", number = "first")
print("Result: %d" %(result))

The sum is: 6
Result: 1


In [10]:
# edit the functions prototype and implementation
def foo(a, b, c, *args):
    return len(args)

def bar(a, b, c, **kwargs):
    return kwargs["magicnumber"] == 7


# test code
if foo(1,2,3,4) == 1:
    print("Good.")
if foo(1,2,3,4,5) == 2:
    print("Better.")
if bar(1,2,3,magicnumber = 6) == False:
    print("Great.")
if bar(1,2,3,magicnumber = 7) == True:
    print("Awesome!")

Good.
Better.
Great.
Awesome!


代码太长可以用\换行：

In [1]:
matrix = [[1,3,2,3,5],\
          [3,4,5,6,3],\
          [2,7,4,3,3],\
          [5,2,2,3,1]]

Python进制的转换，可以通过调节格式输出不带有b的输出值

In [1]:
dec = 11
print("十进制数为：", dec)
print("转换为二进制为：", bin(dec))
print("转换为八进制为：", oct(dec))
print("转换为十六进制为：", hex(dec))

十进制数为： 11
转换为二进制为： 0b1011
转换为八进制为： 0o13
转换为十六进制为： 0xb


比如建模之后的模型是通过ndarray来储存系数的，可以使用numpy.ndarray.tolist或者numpy.ndarray.item来进行提取。

In [7]:
import numpy as np
x = np.random.randint(9, size=(3, 3))
x

x.item(3)

x.item(7)

x.item((0, 1))

x.item((2, 2))


array([[8, 2, 6],
       [2, 5, 2],
       [4, 0, 3]])

2

0

2

3

use df.drop and np.delete to select dataframe or array

In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.arange(12).reshape(3, 4)
b = pd.DataFrame(a)
b

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [16]:
b.drop(labels=0,axis = 1)

1   2   3
0  1   2   3
1  5   6   7
2  9  10  11

In [17]:
conditions = ~b.columns.isin([0])
b.loc[:,conditions]

1   2   3
0  1   2   3
1  5   6   7
2  9  10  11

In [19]:
b.columns.values

array([0, 1, 2, 3], dtype=int64)

In [11]:
np.delete(a,0,axis = 1)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])